package fr.HtSTeam.HtS.Utils;

import org.bukkit.Material;
import org.bukkit.entity.EntityType;

public class MobManager {

	public static Material mobToEgg(EntityType et) {
		switch (et) {
		case ELDER_GUARDIAN:
			return Material.ELDER_GUARDIAN_SPAWN_EGG;
		case WITHER_SKELETON:
			return Material.WITHER_SKELETON_SPAWN_EGG;
		case STRAY:
			return Material.STRAY_SPAWN_EGG;
		case HUSK:
			return Material.HUSK_SPAWN_EGG;
		case ZOMBIE_VILLAGER:
			return Material.ZOMBIE_VILLAGER_SPAWN_EGG;
		case SKELETON_HORSE:
			return Material.SKELETON_HORSE_SPAWN_EGG;
		case ZOMBIE_HORSE:
			return Material.ZOMBIE_HORSE_SPAWN_EGG;
		case DONKEY:
			return Material.DONKEY_SPAWN_EGG;
		case MULE:
			return Material.MULE_SPAWN_EGG;
		case EVOKER:
			return Material.EVOKER_SPAWN_EGG;
		case VEX:
			return Material.VEX_SPAWN_EGG;
		case VINDICATOR:
			return Material.VINDICATOR_SPAWN_EGG;
		case CREEPER:
			return Material.CREEPER_SPAWN_EGG;
		case SKELETON:
			return Material.SKELETON_SPAWN_EGG;
		case SPIDER:
			return Material.SPIDER_SPAWN_EGG;
		case ZOMBIE:
			return Material.ZOMBIE_SPAWN_EGG;
		case SLIME:
			return Material.SLIME_SPAWN_EGG;
		case GHAST:
			return Material.GHAST_SPAWN_EGG;
		case PIG_ZOMBIE:
			return Material.ZOMBIE_PIGMAN_SPAWN_EGG;
		case ENDERMAN:
			return Material.ENDERMAN_SPAWN_EGG;
		case CAVE_SPIDER:
			return Material.CAVE_SPIDER_SPAWN_EGG;
		case SILVERFISH:
			return Material.SILVERFISH_SPAWN_EGG;
		case BLAZE:
			return Material.BLAZE_SPAWN_EGG;
		case MAGMA_CUBE:
			return Material.MAGMA_CUBE_SPAWN_EGG;
		case BAT:
			return Material.BAT_SPAWN_EGG;
		case WITCH:
			return Material.WITCH_SPAWN_EGG;
		case ENDERMITE:
			return Material.ENDERMITE_SPAWN_EGG;
		case GUARDIAN:
			return Material.GUARDIAN_SPAWN_EGG;
		case SHULKER:
			return Material.SHULKER_SPAWN_EGG;
		case PIG:
			return Material.PIG_SPAWN_EGG;
		case SHEEP:
			return Material.SHEEP_SPAWN_EGG;
		case COW:
			return Material.COW_SPAWN_EGG;
		case CHICKEN:
			return Material.CHICKEN_SPAWN_EGG;
		case SQUID:
			return Material.SQUID_SPAWN_EGG;
		case WOLF:
			return Material.WOLF_SPAWN_EGG;
		case MUSHROOM_COW:
			return Material.MOOSHROOM_SPAWN_EGG;
		case OCELOT:
			return Material.OCELOT_SPAWN_EGG;
		case HORSE:
			return Material.HORSE_SPAWN_EGG;
		case RABBIT:
			return Material.RABBIT_SPAWN_EGG;
		case POLAR_BEAR:
			return Material.POLAR_BEAR_SPAWN_EGG;
		case LLAMA:
			return Material.LLAMA_SPAWN_EGG;
		case PARROT:
			return Material.PARROT_SPAWN_EGG;
		case VILLAGER:
			return Material.VILLAGER_SPAWN_EGG;
		case TURTLE:
			return Material.TURTLE_SPAWN_EGG;
		case PHANTOM:
			return Material.PHANTOM_SPAWN_EGG;
		case COD:
			return Material.COD_SPAWN_EGG;
		case SALMON:
			return Material.SALMON_SPAWN_EGG;
		case PUFFERFISH:
			return Material.PUFFERFISH_SPAWN_EGG;
		case TROPICAL_FISH:
			return Material.TROPICAL_FISH_SPAWN_EGG;
		case DROWNED:
			return Material.DROWNED_SPAWN_EGG;
		case DOLPHIN:
			return Material.DOLPHIN_SPAWN_EGG;
		default:
			return null;
		}
	}
	
	public static EntityType eggToMob(Material m) {
		switch (m) {
		case ELDER_GUARDIAN_SPAWN_EGG:
			return EntityType.ELDER_GUARDIAN;
		case WITHER_SKELETON_SPAWN_EGG:
			return EntityType.WITHER_SKELETON;
		case STRAY_SPAWN_EGG:
			return EntityType.STRAY;
		case HUSK_SPAWN_EGG:
			return EntityType.HUSK;
		case ZOMBIE_VILLAGER_SPAWN_EGG:
			return EntityType.ZOMBIE_VILLAGER;
		case SKELETON_HORSE_SPAWN_EGG:
			return EntityType.SKELETON_HORSE;
		case ZOMBIE_HORSE_SPAWN_EGG:
			return EntityType.ZOMBIE_HORSE;
		case DONKEY_SPAWN_EGG:
			return EntityType.DONKEY;
		case MULE_SPAWN_EGG:
			return EntityType.MULE;
		case EVOKER_SPAWN_EGG:
			return EntityType.EVOKER;
		case VEX_SPAWN_EGG:
			return EntityType.VEX;
		case VINDICATOR_SPAWN_EGG:
			return EntityType.VINDICATOR;
		case CREEPER_SPAWN_EGG:
			return EntityType.CREEPER;
		case SKELETON_SPAWN_EGG:
			return EntityType.SKELETON;
		case SPIDER_SPAWN_EGG:
			return EntityType.SPIDER;
		case ZOMBIE_SPAWN_EGG:
			return EntityType.ZOMBIE;
		case SLIME_SPAWN_EGG:
			return EntityType.SLIME;
		case GHAST_SPAWN_EGG:
			return EntityType.GHAST;
		case ZOMBIE_PIGMAN_SPAWN_EGG:
			return EntityType.PIG_ZOMBIE;
		case ENDERMAN_SPAWN_EGG:
			return EntityType.ENDERMAN;
		case CAVE_SPIDER_SPAWN_EGG:
			return EntityType.CAVE_SPIDER;
		case SILVERFISH_SPAWN_EGG:
			return EntityType.SILVERFISH;
		case BLAZE_SPAWN_EGG:
			return EntityType.BLAZE;
		case MAGMA_CUBE_SPAWN_EGG:
			return EntityType.MAGMA_CUBE;
		case BAT_SPAWN_EGG:
			return EntityType.BAT;
		case WITCH_SPAWN_EGG:
			return EntityType.WITCH;
		case ENDERMITE_SPAWN_EGG:
			return EntityType.ENDERMITE;
		case GUARDIAN_SPAWN_EGG:
			return EntityType.GUARDIAN;
		case SHULKER_SPAWN_EGG:
			return EntityType.SHULKER;
		case PIG_SPAWN_EGG:
			return EntityType.PIG;
		case SHEEP_SPAWN_EGG:
			return EntityType.SHEEP;
		case COW_SPAWN_EGG:
			return EntityType.COW;
		case CHICKEN_SPAWN_EGG:
			return EntityType.CHICKEN;
		case SQUID_SPAWN_EGG:
			return EntityType.SQUID;
		case WOLF_SPAWN_EGG:
			return EntityType.WOLF;
		case MOOSHROOM_SPAWN_EGG:
			return EntityType.MUSHROOM_COW;
		case OCELOT_SPAWN_EGG:
			return EntityType.OCELOT;
		case HORSE_SPAWN_EGG:
			return EntityType.HORSE;
		case RABBIT_SPAWN_EGG:
			return EntityType.RABBIT;
		case POLAR_BEAR_SPAWN_EGG:
			return EntityType.POLAR_BEAR;
		case LLAMA_SPAWN_EGG:
			return EntityType.LLAMA;
		case PARROT_SPAWN_EGG:
			return EntityType.PARROT;
		case VILLAGER_SPAWN_EGG:
			return EntityType.VILLAGER;
		case TURTLE_SPAWN_EGG:
			return EntityType.TURTLE;
		case PHANTOM_SPAWN_EGG:
			return EntityType.PHANTOM;
		case COD_SPAWN_EGG:
			return EntityType.COD;
		case SALMON_SPAWN_EGG:
			return EntityType.SALMON;
		case PUFFERFISH_SPAWN_EGG:
			return EntityType.PUFFERFISH;
		case TROPICAL_FISH_SPAWN_EGG:
			return EntityType.TROPICAL_FISH;
		case DROWNED_SPAWN_EGG:
			return EntityType.DROWNED;
		case DOLPHIN_SPAWN_EGG:
			return EntityType.DOLPHIN;
		default:
			return null;
		}
	}
	
}
