name: HtS
version: 1.0
authors: [ikbrunel, theogiraudet]
main: fr.HtSTeam.HtS.Main
commands:
 option:
  description: Ouvre le menu des options
  usage: Erreur syntaxe ! Faites /option
 start: 
  description: Lance la partie
  usage: Erreur syntaxe ! Faites /start
 run:
  description: Force le lancement de la partie
  usage: Erreur syntaxe ! Faites /run
 team:
  description: Commandes relatives aux teams
  usage: Erreur syntaxe ! Faites /team <add|remove|join|leave|list|random> [Equipe] [couleur|Player]
 gui: 
  description: Ouvre l'inventaire des modifiers
  usage: Erreur syntaxe ! Faites /gui
 base:
  description: Défini une base
  usage: Erreur syntaxe ! Faites /base <add|join|list|remove> [nomBase] [nomEquipe]
 load:
  description: Charge un preset
  usage: Erreur syntaxe ! Faites /load (preset)
 pause:
  description: Met en pause le jeu
  usage: Erreur syntaxe ! Faites /pause
 play:
  description: Relance le jeu en cours
  usage: Erreur syntaxe ! Faites /play
 end:
  description: Stop la partie
  usage: Erreur Syntaxe ! Faites /end
 heal:
  description: Heal le joueur
  usage: Erreur ! Faites /heal  <joueur>
 feed:
  description: Nourris le joueur
  usage: Erreur ! Faites /feed <joueur>
 radar:
  description: Radar
  usage: Erreur Syntaxe ! Faites /radar <exemple>
 target:
  description: Target
  usage: Erreur Syntaxe ! Faites /target
  aliases: [cible]
 remove:
  description: Remove
  usage: Erreur Syntaxe ! Faites /remove