name: HtS
version: 1.0
authors: [ikbrunel, theogiraudet]
main: fr.HtSTeam.HtS.Main
api-version: 1.13
commands:
 option:
  description: Ouvre le menu des options
  usage: Erreur syntaxe !
 start: 
  description: Lance la partie
  usage: Erreur syntaxe !
 run:
  description: Force le lancement de la partie
  usage: Erreur syntaxe !
 teams:
  description: Commandes relatives aux teams
  usage: Erreur syntaxe !
 gui: 
  description: Ouvre l'inventaire des modifiers
  usage: Erreur syntaxe !
 base:
  description: Défini une base
  usage: Erreur syntaxe ! Faites /base <add|join|list|remove> [nomBase] [nomEquipe]
 load:
  description: Charge un preset
  usage: Erreur syntaxe !
 pause:
  description: Met en pause le jeu
  usage: Erreur syntaxe !
 play:
  description: Relance le jeu en cours
  usage: Erreur syntaxe !
 end:
  description: Stop la partie
  usage: Erreur Syntaxe !
 heal:
  description: Heal le joueur
  usage: Erreur !
 feed:
  description: Nourris le joueur
  usage: Erreur !
 radar:
  description: Radar
  usage: Erreur Syntaxe !
 target:
  description: Target
  usage: Erreur Syntaxe !
  aliases: [cible]
 remove:
  description: Remove
  usage: Erreur Syntaxe !