name: HtS
version: 1.0
authors: [IkBrunel, theogiraudet]
main: fr.HtSTeam.HtS.Main
commands:
 option:
  description: Ouvre le menu des options
  usage: Erreur syntaxe ! Faites /option
 start: 
  description: Lance la partie
  usage: Erreur syntaxe ! Faites /start
 run:
  descrption: Force le lancement de la partie
  usage: Erreur syntaxe ! Faites /run