name: HtS
version: 1.0
authors: [IkBrunel, theogiraudet]
main: fr.HtSTeam.HtS.Main
commands:
 option:
  description: Ouvre le menu des options
  usage: Erreur syntaxe ! Faites /option
 start: 
  description: Lance la partie
  usage: Erreur syntaxe ! Faites /start
 run:
  description: Force le lancement de la partie
  usage: Erreur syntaxe ! Faites /run
 team:
  description: Commandes relatives aux teams
  usage: Erreur syntaxe ! Faites /team
 gui: 
  description: Ouvre l'inventaire des modifiers
  usage: Erreur syntaxe ! Faites /gui
 base:
  description: Définir une base
  usage: Erreur syntaxe ! Faites /setbase (nomBase) (nomEquipe)